import type { Metadata } from "next";
import { Inter, Open_Sans } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { FC, PropsWithChildren } from "react";
import { Toaster } from "@/components/ui/toaster";

interface RootLayoutProps extends PropsWithChildren {
  params: { locale: string };
}

const inter = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Garimpei Wallet",
  description: "Generated by create next app",
};

const RootLayout: FC<RootLayoutProps> = ({ children, params: { locale } }) => {
  const messages = useMessages();

  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages}>
          {children}
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
};

export default RootLayout;
