name: Docker Build & Publish

on:
  push:
    branches: [main]

  # This workflow dispatch, allows us to execute this workflow manually
  workflow_dispatch:

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_PASSWORD}}

      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/banking-web:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/banking-web:latest
        env:
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET}}
          NEXTAUTH_JWT: ${{ secrets.NEXTAUTH_JWT}}
          NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL}}
          API_URL_AUTH: ${{ secrets.API_URL_AUTH}}
          API_URL_TRANSACTION: ${{ secrets.API_URL_TRANSACTION}}

  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{secrets.DEPLOYMENT_TRIGGER_URL}}
          method: "GET"
